- name: Checking if cloudendure is installed
  win_stat:
          path: '{{window_cloudendure_agent_path}}'
  register: windows_agent_file_stat_result
  when:
          - ansible_os_family == "Windows"

- name: Copying uninstallation file to another location
  win_copy:
          src: '{{windows_cloudendure_uninstallation_directory_source}}'
          dest: '{{windows_cloudendure_uninstallation_directory_destination}}'
          remote_src: True
  when:
          - ansible_os_family == "Windows"
          - windows_agent_file_stat_result.stat.exists == True

- name: running cloudendure uninstallation
  win_command: '{{uninstall_cloudendure_in_windows}}'
  args:
          chdir: '{{windows_cloudendure_uninstallation_file_destination}}'
  when:
          - ansible_os_family == "Windows"
          - windows_agent_file_stat_result.stat.exists == True
